- hosts: default
  roles:
    - app
    - geerlingguy.java
    - {role: geerlingguy.elasticsearch, elasticsearch_network_host: '0.0.0.0'}
    - {role: geerlingguy.ruby, ruby_install_from_source: true, ruby_download_url: 'http://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.gz', ruby_version: '2.4.0'}
  #  - role: gerrlingguy.nginx
  #    nginx_vhosts:
  #
  # - listen: "80 default_server" # default: "80 default_server"
  #   server_name: "example.com" # default: N/A
  #   root: "/var/www/example.com" # default: N/A
  #   index: "index.html index.htm" # default: "index.html index.htm"
  #
  #   # Properties that are only added if defined:
  #   error_page: ""
  #   access_log: ""
  #   error_log: ""
  #   extra_parameters: "" # Can be used to add extra config blocks (multiline).}
