- hosts: default
  roles:
    - geerlingguy.java
    - {role: geerlingguy.elasticsearch, elasticsearch_network_host: '0.0.0.0'}
    - {role: geerlingguy.ruby, ruby_install_from_source: true, ruby_download_url: 'http://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.gz', ruby_version: '2.4.0'}
    - app
    - role: geerlingguy.nginx
      nginx_upstreams:
        - name: app
          servers:
            - "unix:/var/govreposearch/sockets/unicorn.sock fail_timeout=0"
      nginx_vhosts:
        - listen: "80 default_server"
          server_name: "localhost"
          root: "/var/govreposearch/public"
          nginx_keepalive_timeout: "10"
          error_page: "500 502 503 504 /500.html"
          extra_parameters: |
            try_files $uri/index.html $uri @app;

            location @app {
                proxy_pass http://app;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
            }
